package current_package;

import com.google.gwt.xml.client.Node;
import_elements
public class elementName extends extend_element {
properties_fields
constructorget_and_set_propertiesdeserialize_methodserialize_codeapply_property_method}